### Es 1
Hai a disposizione un file `data.csv` contenente dati mensili di traffico aereo con due colonne:

- `date`: data in formato `YYYY-MM` (mese/anno)
- `passengers`: numero di passeggeri per quel mese


Costruisci un modello di **regressione polinomiale** che approssima l’andamento del numero di passeggeri nel tempo.

1. Carica il dataset.
2. Convertilo in un formato numerico utilizzando una colonna `mese_numerico` che conti i mesi a partire da gennaio 1949.
3. Applica una regressione polinomiale (grado a tua scelta).
4. Calcola l’RMSE tra i valori reali e quelli predetti.
5. Visualizza i dati reali e la curva stimata con Plotly.

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import plotly.graph_objects as go
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data.csv")
df.head()

      date  passengers
0  1949-01       112.0
1  1949-02       118.0
2  1949-03       132.0
3  1949-04       129.0
4  1949-05       121.0

In [3]:
df = df.dropna()

In [4]:
df['mese_numerico'] = range(1, len(df) + 1)

In [5]:
df.head()

      date  passengers  mese_numerico
0  1949-01       112.0              1
1  1949-02       118.0              2
2  1949-03       132.0              3
3  1949-04       129.0              4
4  1949-05       121.0              5

In [6]:
X = df[["mese_numerico"]]
y = df[["passengers"]]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, shuffle=False)

In [8]:
degree = 3
model = make_pipeline(
    PolynomialFeatures(degree=degree),
    LinearRegression()
)

model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

rmse_train = root_mean_squared_error(y_train, y_pred_train)
rmse_test = root_mean_squared_error(y_test, y_pred_test)

print("Train RMSE:", rmse_train)
print("Test RMSE:", rmse_test)

Train RMSE: 41.17643238031943
Test RMSE: 71.77064647970376

In [9]:
max_degree = 5
for i in range(1, max_degree+1):
    print(f"\nDegree: {i}")
    model_test_degr = make_pipeline(
        PolynomialFeatures(degree=i),
        LinearRegression()
    )

    model_test_degr.fit(X_train, y_train)
    y_pred_train = model_test_degr.predict(X_train)
    y_pred_test = model_test_degr.predict(X_test)

    rmse_train = root_mean_squared_error(y_train, y_pred_train)
    rmse_test = root_mean_squared_error(y_test, y_pred_test)

    print("Train RMSE:", rmse_train)
    print("Test RMSE:", rmse_test)

Degree: 1
Train RMSE: 42.603271155904395
Test RMSE: 72.08702883043198

Degree: 2
Train RMSE: 41.42498773137669
Test RMSE: 71.90059808299539

Degree: 3
Train RMSE: 41.17643238031943
Test RMSE: 71.77064647970376

Degree: 4
Train RMSE: 40.92062172123343
Test RMSE: 74.47894528587817

Degree: 5
Train RMSE: 39.89498436137442
Test RMSE: 165.8689992594785

In [10]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=X_train["mese_numerico"],
    y=y_train["passengers"],
    mode="markers",
    name="Train"
))

fig.show()

In [11]:
fig.add_trace(go.Scatter(
    x=X_test["mese_numerico"],
    y=y_test["passengers"],
    mode="markers",
    name="Test"
))

fig.show()

In [12]:
fig.add_trace(go.Scatter(
    x=df["mese_numerico"],
    y=model.predict(X).ravel(),
    mode="lines",
    name=f"Regressione polinomiale grado {degree}"
))


fig.show()

In [13]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=X_train["mese_numerico"],
    y=y_train["passengers"],
    mode="markers",
    name="Train"
))

fig.add_trace(go.Scatter(
    x=X_test["mese_numerico"],
    y=y_test["passengers"],
    mode="markers",
    name="Test"
))

fig.add_trace(go.Scatter(
    x=df["mese_numerico"],
    y=model.predict(X).ravel(),
    mode="lines",
    name=f"Regressione polinomiale grado {degree}"
))

fig.show()